# Generated by Django 3.2.6 on 2021-08-30 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagoery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagoery_name', models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
    ]
