# Generated by Django 3.2.6 on 2021-09-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20210830_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='cataegory',
            new_name='catagoery',
        ),
        migrations.AddField(
            model_name='catagoery',
            name='catagoery_description',
            field=models.TextField(null=True),
        ),
    ]
